### ISSUE TITLE
set default time for timestamp column in request entity

### ISSUE THREAD

**Issue by westrachel** [team-aglr/requestbin-backend#12]
I don't think we can insert a current time in the timestamp field when we insert into the requests table with how the schema is currently setup; I think we need to set a default time constraint in the table's creation

**Comment by lukeoguro** [comment]
I think you're right, and I think this is what we're looking for:

```
created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW() AT TIME ZONE 'UTC'
```
