### ISSUE TITLE
Create router for requests (API)

### ISSUE THREAD

**Issue by gcpinckert** [team-aglr/requestbin-backend#21]
code out the `controllers/requests.js` file to fetch request data from the db models.

**Comment by gcpinckert** [comment]
`controllers/requests.js` is responsible for:

- the API route for getting all requests pertaining to a specific bin (just the metadata in PSQL)
- the API route for returning a specific request from a specific bin (this includes actual request data stored in Mongo and the metadata stored in PSQL)

**Comment by lukeoguro** [comment]
Done in 34ecc3293291c608ec102f2412a530c3069dc98c
