### ISSUE TITLE
clarify request and bin (API) router paths in `app.js`

### ISSUE THREAD

**Issue by gcpinckert** [team-aglr/requestbin-backend#25]
Just need to make some small adjustments in `app.js` pertaining to the following:

- create a controller for bins
- create a controller for requests
- In app.js, do the following:

```js
router.use(/api/bins/:uuid/requests, requestController)
router.use(/api/bins, binController)
```

So `controllers/requests.js` is responsible for:
- the API route for getting all requests pertaining to a specific bin (just the metadata in PSQL)
- the API route for returning a specific request from a specific bin (this includes actual request data stored in Mongo and the metadata stored in PSQL)

And `controllers/bins.js` is responsible for:
- the API route for getting all bins
- the API route for creating a new bin

**Comment by lukeoguro** [comment]
Added in 872718990e28ac56a3765be787e1bc48a8055eae
