### ISSUE TITLE
Test the "/api/collect" route using ngrok

### ISSUE THREAD

**Issue by elguaposalsero** [team-aglr/requestbin-backend#32]
Here are instructions on how to test: [coda link](https://coda.io/d/Request-Bin-Project_dhINF_EGjTf/00-Documentation_sugx8#_luHMR)

**Comment by gcpinckert** [comment]
This was fixed by commit [47f084b](https://github.com/team-aglr/requestbin-backend/commit/47f084b77b9b59623c3a3e3de4472961774ed983)
