### ISSUE TITLE
Returning an empty list of requests instead of a 404

### ISSUE THREAD

**Issue by lukeoguro** [team-aglr/requestbin-backend#38]
Hey @gcpinckert in the requests controller, could you just return an empty array instead of a 404? Let me know your thoughts

**Comment by gcpinckert** [comment]
Yeah, that's a fantastic point. I had in my head that empty array meant no bin, as this is what is returned in cases of something like `api/bins/malformatUUID` but I didn't consider the situation where a bin is empty. I'll implement something else to deal with cases of bad UUID params. Thanks for the heads up!

**Comment by lukeoguro** [comment]
Only reason I'm suggesting this is because when I was testing your controller, I freaked out when I got the 404, even though I *just* got it working 5 min ago 😂

**Comment by gcpinckert** [comment]
No it makes total sense! I'm glad you pointed it out, sorry for freaking you out!

**Comment by gcpinckert** [comment]
I need the function from [this PR](https://github.com/team-aglr/requestbin-backend/pull/41) pulled into main before I can implement a fix for this.
